spring:
  application:
    name: api-usuarios

datasource:
  url: jdbc:mysql://localhost:3309/bd_api_usuarios?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
  user: coti
  pass: Coti@2026
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 2c3370b8-ff54-4897-8234-e4c1c3103151
  expiration: 3600000

cors:
  frontend: http://localhost:4200/